<a href="https://colab.research.google.com/github/devyadav11/ML_tryouts/blob/main/Notes_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import torch.nn as nn
import torch.optim as optim

import pandas as pd
import math
import torch
import torchvision
import torch.nn.functional as F  # Parameterless functions, like (some) activation functions
import torchvision.datasets as datasets  # Standard datasets
import torchvision.transforms as transforms  # Transformations we can perform on our dataset for augmentation
from torch import optim  # For optimizers like SGD, Adam, etc.
from torch import nn  # All neural network modules
from torch.utils.data import ( DataLoader, random_split)                    # Gives easier dataset managment by creating mini batches etc.
from tqdm import tqdm                                                       # For nice progress bar!

from torchvision.datasets import ImageFolder
import os
import random
import matplotlib.pyplot as plt
import numpy as np
import pathlib

In [65]:
# 1.  zip = combine multiple iterables (like lists or tuples) element-wise into tuples. It's like pairing items together by their positions.

a = [1, 2, 3]
b = ['a', 'b', 'c']

zipped = zip(a, b)
print(list(zipped))

for num, char in zip(a, b):
    print(num, char)



[(1, 'a'), (2, 'b'), (3, 'c')]
1 a
2 b
3 c


In [173]:
words = open('names.txt', 'r').read().splitlines()
print(words[:10])

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia', 'harper', 'evelyn']


In [174]:
b = {}
for w in words:
  chs = ['<s>'] + list(w) + ['<e>']
  for ch1, ch2 in zip(chs, chs[1:]):
    bigram = (ch1, ch2)
    b[bigram] = b.get(bigram, 0) + 1



Streaming output truncated to the last 5000 lines.
u i
i s
s e
e n
n r
r i
i q
q u
u e
e <e>
<s> l
l u
u i
i s
s m
m i
i g
g u
u e
e l
l <e>
<s> l
l u
u k
k m
m a
a n
n <e>
<s> l
l u
u n
n a
a <e>
<s> l
l u
u v
v <e>
<s> l
l y
y n
n t
t o
o n
n <e>
<s> l
l y
y o
o n
n s
s <e>
<s> l
l y
y t
t e
e <e>
<s> m
m a
a a
a d
d h
h a
a v
v <e>
<s> m
m a
a c
c c
c a
a b
b e
e e
e <e>
<s> m
m a
a c
c i
i e
e j
j <e>
<s> m
m a
a c
c k
k s
s <e>
<s> m
m a
a c
c l
l a
a r
r e
e n
n <e>
<s> m
m a
a d
d e
e l
l i
i n
n e
e <e>
<s> m
m a
a g
g d
d a
a l
l e
e n
n o
o <e>
<s> m
m a
a h
h a
a n
n <e>
<s> m
m a
a h
h a
a v
v i
i r
r <e>
<s> m
m a
a h
h i
i l
l a
a n
n <e>
<s> m
m a
a j
j e
e e
e d
d <e>
<s> m
m a
a k
k a
a d
d e
e n
n <e>
<s> m
m a
a k
k s
s e
e n
n <e>
<s> m
m a
a k
k s
s o
o n
n <e>
<s> m
m a
a l
l a
a c
c k
k i
i <e>
<s> m
m a
a l
l a
a k
k i
i a
a h
h <e>
<s> m
m a
a l
l l
l i
i k
k <e>
<s> m
m a
a l
l o
o <e>
<s> m
m a
a l
l y
y k
k a
a i
i <e>
<s> m
m a
a m
m o
o u
u d
d o
o u
u <e>

In [122]:
x = torch.Generator().manual_seed(12345)  # fixes the random numbers
g = torch.rand(1,5, generator=x)
g = g/g.sum()
print(g)
g.float()

tensor([[0.2889, 0.2589, 0.2920, 0.1357, 0.0245]])


tensor([[0.2889, 0.2589, 0.2920, 0.1357, 0.0245]])

In [124]:
g = torch.multinomial(g, num_samples = 10, replacement=True, generator = x)
g

tensor([[4, 2, 1, 1, 1, 1, 0, 1, 0, 1]])