<a href="https://colab.research.google.com/github/devyadav11/ML_tryouts/blob/main/Notes_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import torch.nn as nn
import torch.optim as optim

import pandas as pd
import math
import torch
import torchvision
import torch.nn.functional as F  # Parameterless functions, like (some) activation functions
import torchvision.datasets as datasets  # Standard datasets
import torchvision.transforms as transforms  # Transformations we can perform on our dataset for augmentation
from torch import optim  # For optimizers like SGD, Adam, etc.
from torch import nn  # All neural network modules
from torch.utils.data import ( DataLoader, random_split)                    # Gives easier dataset managment by creating mini batches etc.
from tqdm import tqdm                                                       # For nice progress bar!

from torchvision.datasets import ImageFolder
import os
import random
import matplotlib.pyplot as plt
import numpy as np
import pathlib

In [65]:
# 1.  zip = combine multiple iterables (like lists or tuples) element-wise into tuples. It's like pairing items together by their positions.

a = [1, 2, 3]
b = ['a', 'b', 'c']

zipped = zip(a, b)
print(list(zipped))

for num, char in zip(a, b):
    print(num, char)



[(1, 'a'), (2, 'b'), (3, 'c')]
1 a
2 b
3 c


In [66]:
x = ['devyadav','ankit', 4] +[2,3]
y = x + [12,13,14]
print(y)

['devyadav', 'ankit', 4, 2, 3, 12, 13, 14]


In [122]:
x = torch.Generator().manual_seed(12345)
g = torch.rand(1,5, generator=x)
g = g/g.sum()
print(g)
g.float()

tensor([[0.2889, 0.2589, 0.2920, 0.1357, 0.0245]])


tensor([[0.2889, 0.2589, 0.2920, 0.1357, 0.0245]])

In [124]:
g = torch.multinomial(g, num_samples = 10, replacement=True, generator = x)
g

tensor([[4, 2, 1, 1, 1, 1, 0, 1, 0, 1]])